### PR TITLE
Add Adwaita theme

### PR DESCRIPTION
**Pull request by metal3d**
The color scheme is generated with:

`go generate ./theme`

It fetches the palette from Adwaita documentation page.

### CODE REVIEW

**Review by andydotxyz — CHANGES_REQUESTED** [review]
Great stuff thanks.

However some of the colour mapping isn't right. The colour names (blue/green etc) are just used where user may desire a different primary colour (see fyne_settings). So you should map instead to the semantic names primary/success/warning/error, which is pretty much 1:1 match.

Or both, to provide consistency for both areas.

**Comment by metal3d** [comment]
I need to add Green, Red, Brown... colors... That would be more consistent. Let me a few minutes to add them.

**Comment by metal3d** [comment]
@andydotxyz I'm not sure if you've seen I made requested changes 😉

**Comment by andydotxyz** [comment]
> @andydotxyz I'm not sure if you've seen I made requested changes 😉

Apologies I did miss this - been a busy week!

**Review by andydotxyz — APPROVED** [review]
This is great, thanks so much!

**Pull request merged**
