### PR TITLE
Theme adwaita - icons and enhancements

### PR DESCRIPTION
**Pull request by metal3d**
This PR proposes a better generator and to bundle icons.

- The colors are written with better syntax (fully named properties for colors)
- Icons are taken from the Adwaita icons repository (https://gitlab.gnome.org/GNOME/adwaita-icon-theme) and converted into `fyne.Resource` + "Themed" if there are "symbolic" (all icons are SVG)
- Fallback to fyne icons when we don't have the corresponding icon
- Place the license reference in the generated sources

These icons are, at this time, not converted from Adwaita (checked when resolved):

- [ ] IconNameColorAchromatic no icon found
- [ ] IconNameColorChromatic no icon found
- [x] IconNameColorPalette not relevent icon
- [x] IconNameFile not sure of the icon to use
- [ ] IconNameLogin no icon found

Don't hesitate to tell me which icon is badly choosen or ideas for not set icons (above).

### CODE REVIEW

**Comment by andydotxyz** [comment]
This looks completely amazing update thanks.
Unfortunately I don't have a suitable system to test on I don't think (my Linux is FyneDesk and X utils).
Any others of the team on Linux and have a good Gnome setup?

**Comment by Jacalz** [comment]
I can check it out sometime next week. Gnome on Fedora is my main desktop environment :)

**Comment by andydotxyz** [comment]
@Jacalz just bumping this as you were going to check it out. I don't have Gnome running (at least not well ;) ).

**Review by Jacalz — COMMENTED** [review]
Thanks for working on this. It is very cool. I just can't seem to get the icons working. All I did was to set the theme to the &Adwaita struct.

image

**Comment by metal3d** [comment]
> Thanks for working on this. It is very cool. I just can't seem to get the icons working. All I did was to set the theme to the &Adwaita struct.
> 
> image

Weird...

```
go mod edit -replace "fyne.io/x/fyne=github.com/metal3d/fyne-x@theme-adwaita"
go mod tidy
```

All the icons are set, whatever the project, even the one on FlatHub => https://flathub.org/fr/apps/org.metal3d.scoreboard

Are you sure to have taken the right branch?

**Comment by Jacalz** [comment]
Hmm. Maybe not. I'll have a look later today. Sorry

**Comment by Jacalz** [comment]
It is definitely working on my laptop now when doing a quick test. Will have to see later today if I did something wrong on my workstation. 

image

It might require some some size changes for v2.4.0? It seems to me like the text is very small and the blue line below the tabs is very big. In general though it looks wonderful. Nice work :)

**Comment by metal3d** [comment]
> It might require some some size changes for v2.4.0? It seems to me like the text is very small and the blue line below the tabs is very big. In general though it looks wonderful. Nice work :)

Thanks a lot 😄 

I probably leave a font scaling test by error. Sorry...

I will remove it if it's true.

**Review by Jacalz — APPROVED** [review]
This looks great. Thank you :)
image

**Comment by Jacalz** [comment]
I see that there are checkboxes left in the description. Are you fine with me merging or do you want to wait? :) @metal3d

**Comment by andydotxyz** [comment]
Let's just get this in - there will often be icons missing as we keep expending the main theme anyway.

**Comment by metal3d** [comment]
> I see that there are checkboxes left in the description. Are you fine with me merging or do you want to wait? :) @metal3d

Sorry for this, actually I kept default for the icons I'm not sure, or if the Adwaita icon is not exactly what we mean in Fyne.

Anyway, I could, later, enhance the icon set.

**Pull request merged**
